#!/usr/bin/env python3
"""
Noise Ablation Study Visualization (ICML Rebuttal)

Compares PRISM v34.1b (clean) vs noise2 (2-flip) vs noise4 (4-flip)
across perplexity, binding affinity, and developability benchmarks.

Note: Uses pd.read_pickle for loading PRISM project data files (.pkl).
These are trusted internal project files generated by our own scripts.
"""

import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import pandas as pd
from scipy.stats import spearmanr

REPO = Path(__file__).resolve().parents[2]
OUT_DIR = REPO / "script" / "analyze" / "reviewer_figures"
OUT_DIR.mkdir(exist_ok=True)

# Color scheme
C_CLEAN = "#2166ac"   # blue
C_NOISE2 = "#f4a582"  # salmon
C_NOISE4 = "#b2182b"  # red
COLORS = [C_CLEAN, C_NOISE2, C_NOISE4]
LABELS = ["PRISM (clean)", "PRISM +noise2", "PRISM +noise4"]


# =========================================================================
# 1. Perplexity
# =========================================================================
def load_pppl():
    """Load pseudo-perplexity for all 3 models."""
    # These are trusted internal project pickle files
    df_base = pd.read_pickle(REPO / "data/prism_results/1.pppl_calculation/OAS_test_pseudo_perplexity_v34_1b_1c.pkl")
    df_n2 = pd.read_pickle(REPO / "data/prism_results/1.pppl_calculation/OAS_test_pppl_noise2.pkl")
    df_n4 = pd.read_pickle(REPO / "data/prism_results/1.pppl_calculation/OAS_test_pppl_noise4.pkl")

    # Standard PP columns (non-normalized)
    col_v34 = "ESM2_v34.1b_paired_cdr_ngl_focus_bugfix_PP"
    col_n2 = "ESM2_v34.1b_noise2flip_rebuttal_PP"
    col_n4 = "ESM2_v34.1b_noise4flip_rebuttal_PP"
    col_v34_marg = "ESM2_v34.1b_paired_cdr_ngl_focus_bugfix_Marg_PP"
    col_n2_marg = "ESM2_v34.1b_noise2flip_rebuttal_Marg_PP"
    col_n4_marg = "ESM2_v34.1b_noise4flip_rebuttal_Marg_PP"

    # Also include baselines
    baselines = {
        "ESM2-35M": df_base["ESM2_35M_PP"],
        "ESM2-650M": df_base["ESM2_650M_PP"],
        "AntiBERTy": df_base["AntiBERTy_PP"],
        "AbLang2": df_base["AbLang2_PP"],
    }

    return {
        "final": {
            "clean": df_base[col_v34].dropna(),
            "noise2": df_n2[col_n2].dropna(),
            "noise4": df_n4[col_n4].dropna(),
        },
        "marg": {
            "clean": df_base[col_v34_marg].dropna(),
            "noise2": df_n2[col_n2_marg].dropna(),
            "noise4": df_n4[col_n4_marg].dropna(),
        },
        "baselines": baselines,
    }


# =========================================================================
# 2. 3DMS Binding Affinity
# =========================================================================
def load_3dms_binding():
    """Compute Spearman rho for 3DMS datasets."""
    datasets = {
        "G6.31": {
            "clean": REPO / "data/antibody_binding/g6.31_benchmark_data_output3.csv",
            "noise2": REPO / "data/antibody_binding/g6.31_benchmark_data_noise2.csv",
            "noise4": REPO / "data/antibody_binding/g6.31_benchmark_data_noise4.csv",
        },
        "CR9114": {
            "clean": REPO / "data/antibody_binding/cr9114_benchmark_data_output3.csv",
            "noise2": REPO / "data/antibody_binding/cr9114_benchmark_data_noise2.csv",
            "noise4": REPO / "data/antibody_binding/cr9114_benchmark_data_noise4.csv",
        },
        "Trastuzumab": {
            "clean": REPO / "data/antibody_binding/trastuzumab_dataset_trimmed_output4.csv",
            "noise2": REPO / "data/antibody_binding/trastuzumab_benchmark_noise2.csv",
            "noise4": REPO / "data/antibody_binding/trastuzumab_benchmark_noise4.csv",
        },
    }

    score_candidates = ["evo_ab_score", "evo_ab_affinity_score"]
    results = {}
    for ds_name, files in datasets.items():
        results[ds_name] = {}
        for model_tag, fpath in files.items():
            if not fpath.exists():
                results[ds_name][model_tag] = np.nan
                continue
            df = pd.read_csv(fpath)
            df = df[df["Mutations"] != "WT"].copy()
            score_col = None
            for sc in score_candidates:
                if sc in df.columns:
                    score_col = sc
                    break
            if score_col is None:
                results[ds_name][model_tag] = np.nan
                continue
            valid = df[score_col].notna() & df["fitness"].notna() & (df[score_col] != 0)
            if valid.sum() > 10:
                rho, _ = spearmanr(df.loc[valid, score_col], df.loc[valid, "fitness"])
                results[ds_name][model_tag] = rho
            else:
                results[ds_name][model_tag] = np.nan
    return results


# =========================================================================
# 3. FLAb2 Developability
# =========================================================================
def load_flab2_developability():
    """Best |Spearman| per property per model (prism vs noise2 vs noise4)."""
    fpath = REPO / "data/features/evaluation_results/flab2_developability/per_antibody_scores.csv"
    if not fpath.exists():
        return {}
    df = pd.read_csv(fpath)

    # Also check for noise4 file
    fpath_n4 = REPO / "data/features/evaluation_results/flab2_developability/per_antibody_scores_noise4.csv"
    if fpath_n4.exists():
        df_n4 = pd.read_csv(fpath_n4)
        df = pd.concat([df, df_n4], ignore_index=True)

    model_map = {"prism": "clean", "prism_noise2": "noise2", "prism_noise4": "noise4"}

    results = {}
    for prop in df["property"].unique():
        results[prop] = {}
        for model_key, tag in model_map.items():
            sub = df[(df["property"] == prop) & (df["model"] == model_key)]
            if sub.empty:
                results[prop][tag] = np.nan
                continue
            best_rho = 0
            for sig in sub["signal"].unique():
                sub_sig = sub[sub["signal"] == sig]
                valid = sub_sig["score"].notna() & sub_sig["fitness"].notna()
                if valid.sum() > 10:
                    rho, _ = spearmanr(sub_sig.loc[valid, "score"], sub_sig.loc[valid, "fitness"])
                    if abs(rho) > abs(best_rho):
                        best_rho = rho
            results[prop][tag] = best_rho
    return results


# =========================================================================
# Plot: Multi-panel figure
# =========================================================================
def make_figure():
    pppl = load_pppl()
    dms = load_3dms_binding()
    flab2_dev = load_flab2_developability()

    fig = plt.figure(figsize=(16, 10))
    gs = gridspec.GridSpec(2, 2, hspace=0.35, wspace=0.3,
                           left=0.07, right=0.97, top=0.93, bottom=0.08)

    tags = ["clean", "noise2", "noise4"]
    width = 0.25

    # --- Panel A: Perplexity box plot ---
    ax1 = fig.add_subplot(gs[0, 0])
    pppl_data = [pppl["marg"]["clean"], pppl["marg"]["noise2"], pppl["marg"]["noise4"]]
    medians = [d.median() for d in pppl_data]

    bps = ax1.boxplot(pppl_data, positions=[1, 2, 3], widths=0.5,
                       patch_artist=True, showfliers=False, whis=[5, 95])
    for patch, color in zip(bps["boxes"], COLORS):
        patch.set_facecolor(color)
        patch.set_alpha(0.7)
    for median_line in bps["medians"]:
        median_line.set_color("black")
        median_line.set_linewidth(1.5)

    # Add median annotations
    for i, med in enumerate(medians):
        ax1.text(i + 1, med + 0.3, f"{med:.2f}", ha="center", va="bottom",
                 fontsize=9, fontweight="bold")

    # Add baseline reference lines
    for bname, bdata in pppl["baselines"].items():
        bmed = bdata.dropna().median()
        ax1.axhline(bmed, color="gray", ls="--", alpha=0.4, lw=0.8)
        ax1.text(3.55, bmed, bname, fontsize=7, va="center", color="gray")

    ax1.set_xticks([1, 2, 3])
    ax1.set_xticklabels(["Clean", "+Noise2", "+Noise4"], fontsize=10)
    ax1.set_ylabel("Pseudo-Perplexity (marginalized)", fontsize=10)
    ax1.set_title("A. Pseudo-Perplexity (OAS test, n=22,591)", fontsize=11, fontweight="bold")
    ax1.set_xlim(0.3, 4.3)

    # --- Panel B: 3DMS Binding Spearman ---
    ax2 = fig.add_subplot(gs[0, 1])
    ds_names = list(dms.keys())
    n_ds = len(ds_names)
    x = np.arange(n_ds)

    for i, (tag, color, label) in enumerate(zip(tags, COLORS, LABELS)):
        vals = [dms[ds].get(tag, np.nan) for ds in ds_names]
        valid_vals = [v if not np.isnan(v) else 0 for v in vals]
        valid_mask = [not np.isnan(v) for v in vals]
        bars = ax2.bar(x + (i - 1) * width, valid_vals, width, label=label,
                        color=color, alpha=0.85, edgecolor="white", linewidth=0.5)
        for j, (v, m) in enumerate(zip(valid_vals, valid_mask)):
            if m and v != 0:
                va = "bottom" if v > 0 else "top"
                offset = 0.01 if v > 0 else -0.01
                ax2.text(x[j] + (i - 1) * width, v + offset, f"{v:.3f}",
                         ha="center", va=va, fontsize=7, rotation=90)
            if not m:
                ax2.text(x[j] + (i - 1) * width, 0.01, "?",
                         ha="center", va="bottom", fontsize=10, color=color, fontweight="bold")

    ax2.set_xticks(x)
    ax2.set_xticklabels(ds_names, fontsize=10)
    ax2.set_ylabel("Spearman ρ (binding affinity)", fontsize=10)
    ax2.set_title("B. 3DMS Binding Affinity (evo_ab_score)", fontsize=11, fontweight="bold")
    ax2.legend(fontsize=8, loc="upper left")
    ax2.axhline(0, color="black", lw=0.5)

    # --- Panel C: FLAb2 Developability ---
    ax3 = fig.add_subplot(gs[1, 0])
    if flab2_dev:
        prop_names = list(flab2_dev.keys())
        prop_labels_short = {
            "self_interaction": "Self-Int.",
            "thermostability": "Thermo.",
            "immunogenicity": "Immuno.",
            "polyreactivity": "Polyreact.",
            "expression": "Express.",
        }
        labels_disp = [prop_labels_short.get(p, p) for p in prop_names]
        n_p = len(prop_names)
        x = np.arange(n_p)

        for i, (tag, color, label) in enumerate(zip(tags, COLORS, LABELS)):
            vals = [abs(flab2_dev[p].get(tag, np.nan)) for p in prop_names]
            valid_vals = [v if not np.isnan(v) else 0 for v in vals]
            valid_mask = [not np.isnan(v) for v in vals]
            ax3.bar(x + (i - 1) * width, valid_vals, width, label=label,
                    color=color, alpha=0.85, edgecolor="white", linewidth=0.5)
            for j, (v, m) in enumerate(zip(valid_vals, valid_mask)):
                if m and v != 0:
                    ax3.text(x[j] + (i - 1) * width, v + 0.005, f"{v:.3f}",
                             ha="center", va="bottom", fontsize=7, rotation=90)
                if not m:
                    ax3.text(x[j] + (i - 1) * width, 0.005, "?",
                             ha="center", va="bottom", fontsize=10, color=color, fontweight="bold")

        ax3.set_xticks(x)
        ax3.set_xticklabels(labels_disp, fontsize=9)
        ax3.set_ylabel("|Spearman ρ| (best signal)", fontsize=10)
        ax3.set_title("C. FLAb2 Developability (5 properties)", fontsize=11, fontweight="bold")
        ax3.legend(fontsize=8, loc="upper right")

    # --- Panel D: Summary table ---
    ax4 = fig.add_subplot(gs[1, 1])
    ax4.axis("off")

    table_data = []
    header = ["Metric", "Clean", "+Noise2", "+Noise4"]

    # PPL medians
    table_data.append(["PPPL (median)", f"{pppl['marg']['clean'].median():.2f}",
                       f"{pppl['marg']['noise2'].median():.2f}",
                       f"{pppl['marg']['noise4'].median():.2f}"])

    # 3DMS mean |rho|
    for ds in dms:
        row = [f"3DMS {ds}"]
        for tag in tags:
            v = dms[ds].get(tag, np.nan)
            row.append(f"{v:.3f}" if not np.isnan(v) else "—")
        table_data.append(row)

    # FLAb2 dev |rho|
    if flab2_dev:
        for prop in flab2_dev:
            row = [f"FLAb2 {prop[:12]}"]
            for tag in tags:
                v = flab2_dev[prop].get(tag, np.nan)
                row.append(f"{abs(v):.3f}" if not np.isnan(v) else "—")
            table_data.append(row)

    tbl = ax4.table(cellText=table_data, colLabels=header,
                     cellLoc="center", loc="center",
                     colColours=["#e0e0e0", C_CLEAN + "40", C_NOISE2 + "40", C_NOISE4 + "40"])
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(8.5)
    tbl.scale(1.0, 1.35)

    for j in range(len(header)):
        tbl[0, j].set_text_props(fontweight="bold")

    for i in range(1, len(table_data) + 1):
        for j in range(1, 4):
            cell = tbl[i, j]
            text = cell.get_text().get_text()
            if text == "—":
                cell.set_facecolor("#f5f5f5")

    ax4.set_title("D. Summary (Spearman ρ or PPPL)", fontsize=11, fontweight="bold", pad=15)

    fig.suptitle("Effect of GL/NGL Label Noise on PRISM Performance",
                 fontsize=14, fontweight="bold", y=0.98)

    out_path = OUT_DIR / "fig_noise_ablation.pdf"
    fig.savefig(out_path, dpi=150)
    fig.savefig(out_path.with_suffix(".png"), dpi=200)
    print(f"Saved: {out_path}")
    print(f"Saved: {out_path.with_suffix('.png')}")
    plt.close(fig)


if __name__ == "__main__":
    make_figure()
